# Generated by Django 5.1.6 on 2025-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='yoomoney_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
